# Generated by Django 4.1.7 on 2023-03-25 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactenquiry',
            name='name',
            field=models.CharField(default=2, max_length=100, null=None),
            preserve_default=False,
        ),
    ]
