# Generated by Django 4.1.7 on 2023-05-19 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_image_category_alter_image_image_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='subcategory',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='image',
            name='image_file',
            field=models.ImageField(upload_to='shop/images'),
        ),
    ]
